POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
  client.global.set("auth_token", response.body.token);
%}
###

GET http://localhost:8080/api/auth
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}

###

GET http://localhost:8080/api/drives
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}
###

DELETE http://localhost:8080/api/drives/67e55044-10b1-426f-9247-bb680e5fe0c8
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}
###


GET http://localhost:8080/api/files/list
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}

{
  "drive": "67e55044-10b1-426f-9247-bb680e5fe0c8",
  "path": "/"
}
###
GET http://localhost:8080/api/files/view
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}

{
  "drive": "67e55044-10b1-426f-9247-bb680e5fe0c8",
  "path": "/file.txt"
}
###

DELETE http://localhost:8080/api/auth
Accept: application/json
Content-Type: application/json
X-Token: {{auth_token}}

###